"""add order status

Revision ID: 815069863dc1
Revises: 16aa9b9c7e44
Create Date: 2026-06-24 16:44:26.732039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '815069863dc1'
down_revision: Union[str, Sequence[str], None] = '16aa9b9c7e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_amount', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
